# Introduction Numpy/Pandas

In [4]:
%pip install pandas numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
import pandas as pd

In [6]:
vect1 = np.arange(0, 9)
vect1.shape

(9,)

In [7]:
print(vect1)

[0 1 2 3 4 5 6 7 8]


In [8]:
matrix = vect1.reshape(3, 3)
matrix.shape

(3, 3)

In [9]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

print(arr + arr2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [11]:
np_arr = np.arange(0, 9)
np_arr = np_arr.reshape(3, 3)

In [12]:
np_arr2 = np.arange(9, 0)
np_arr2 = np_arr.reshape(3, 3)

In [14]:
np_arr + np_arr2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [219]:
np.transpose(np_arr)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [220]:
np_arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [15]:
import sys
import array

In [17]:
big_list = list(range(1_000_000))
print(sys.getsizeof(big_list))
%timeit sum(big_list)

8000056
2.76 ms ± 136 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
big_array = np.arange(1_000_000)
%timeit np.sum(big_array)

102 μs ± 2.65 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Array

Créer un tableau

In [20]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [21]:
print(np.arange(0, 9, 2))

[0 2 4 6 8]


In [22]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [23]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
print(np.random.randint(-1, 5, (5,5)))

[[ 1  4  0  3  3]
 [-1  0  1  3  0]
 [ 3  1  4  2  2]
 [ 3 -1  3  3  0]
 [ 1  3  4  2  4]]


In [31]:
print(np.random.normal(5, 1, (2, 3))) # mean std shape

[[4.02482449 2.55630421 5.45944016]
 [4.73387125 7.08585152 4.63516917]]


# Data types

* np.int32 / np.int64
* np.float64
* np.uint8 / np.uint16 / np.uint32 / np.uint64

In [32]:
arr_int = np.array([1,2,3], dtype=np.int64)
arr_int

array([1, 2, 3])

In [ ]:
arr_float = arr_int.astype(np.float64)

In [52]:
arr_float2 = np.array([[1,2,3.14], [5, 6, 7]], dtype=np.float64)
arr_float2

array([[1.  , 2.  , 3.14],
       [5.  , 6.  , 7.  ]])

In [44]:
print("ndim : ", arr_float2.ndim)
print("size : ", arr_float2.size)
print("shape : ", arr_float2.shape)
print("dtype : ", arr_float2.dtype)
print("itemsize : ", arr_float2.itemsize) # Taille de chaque élément en mémoire (64bit = 8bytes)
print("nbytes : ", arr_float2.nbytes) # Taille total de mon tableau en mémoire en bytes.

ndim :  1
size :  3
shape :  (3,)
dtype :  float64
itemsize :  8
nbytes :  24


In [50]:
try:
    arr_int2 = arr_float2.astype(np.int64)
    arr_int2[0,0] = np.nan
    print(arr_float2)
except Exception as err:
    print(err)

cannot convert float NaN to integer


/tmp/ipykernel_16269/3804407234.py:2: RuntimeWarning: invalid value encountered in cast
  arr_int2 = arr_float2.astype(np.int64)


In [53]:
for el in [np.array([]), np.nan, np.inf, np.int32, np.uint8, np.float16, np.float32, np.float64]:
    print(el, ':', type(el))

[] : <class 'numpy.ndarray'>
nan : <class 'float'>
inf : <class 'float'>
<class 'numpy.int32'> : <class 'type'>
<class 'numpy.uint8'> : <class 'type'>
<class 'numpy.float16'> : <class 'type'>
<class 'numpy.float32'> : <class 'type'>
<class 'numpy.float64'> : <class 'type'>


In [54]:
print(np.inf +1)
print(1 / np.inf)
print(np.inf * np.inf)
print(np.inf - np.inf)

inf
0.0
inf
nan


# Opérations sur les tableaux

In [55]:
arr_2 = np.arange(5, 0, -1)

arr_2

array([5, 4, 3, 2, 1])

In [56]:
arr_2 + 2

array([7, 6, 5, 4, 3])

In [58]:
arr_2 * 2

array([10,  8,  6,  4,  2])

In [59]:
arr_2 % 2

array([1, 0, 1, 0, 1])

In [60]:
(arr_2 * 2) < 5

array([False, False, False,  True,  True])

In [61]:
arr_2[(arr_2 * 2) < 5]

array([2, 1])

# Broadcasting

In [62]:
arr_2d = np.random.random((5, 5))
arr_2d

array([[0.21057858, 0.56604212, 0.84251317, 0.90313239, 0.9501487 ],
       [0.46818483, 0.75421997, 0.73175844, 0.79193323, 0.24665429],
       [0.08998153, 0.75165821, 0.40481135, 0.3278164 , 0.40786524],
       [0.0379207 , 0.63475818, 0.95131821, 0.26350739, 0.08377213],
       [0.70903705, 0.06147773, 0.20171277, 0.18117485, 0.32202554]])

In [63]:
arr_2d + 10

array([[10.21057858, 10.56604212, 10.84251317, 10.90313239, 10.9501487 ],
       [10.46818483, 10.75421997, 10.73175844, 10.79193323, 10.24665429],
       [10.08998153, 10.75165821, 10.40481135, 10.3278164 , 10.40786524],
       [10.0379207 , 10.63475818, 10.95131821, 10.26350739, 10.08377213],
       [10.70903705, 10.06147773, 10.20171277, 10.18117485, 10.32202554]])

In [65]:
arr_2d + np.array([0, 0, 10, 5, 3])

array([[ 0.21057858,  0.56604212, 10.84251317,  5.90313239,  3.9501487 ],
       [ 0.46818483,  0.75421997, 10.73175844,  5.79193323,  3.24665429],
       [ 0.08998153,  0.75165821, 10.40481135,  5.3278164 ,  3.40786524],
       [ 0.0379207 ,  0.63475818, 10.95131821,  5.26350739,  3.08377213],
       [ 0.70903705,  0.06147773, 10.20171277,  5.18117485,  3.32202554]])

In [66]:
np.array([0, 0, 10, 5, 3]).reshape((-1, 1))

array([[ 0],
       [ 0],
       [10],
       [ 5],
       [ 3]])

In [67]:
arr_2d + np.array([0, 0, 10, 5, 3]).reshape((-1, 1))

array([[ 0.21057858,  0.56604212,  0.84251317,  0.90313239,  0.9501487 ],
       [ 0.46818483,  0.75421997,  0.73175844,  0.79193323,  0.24665429],
       [10.08998153, 10.75165821, 10.40481135, 10.3278164 , 10.40786524],
       [ 5.0379207 ,  5.63475818,  5.95131821,  5.26350739,  5.08377213],
       [ 3.70903705,  3.06147773,  3.20171277,  3.18117485,  3.32202554]])

In [68]:
np.array([0, 0, 10, 5, 3])

array([ 0,  0, 10,  5,  3])

In [70]:
print((np.array([0, 0, 10, 5, 3]).reshape(1, -1)))

[[ 0  0 10  5  3]]


In [72]:
print((np.array([0, 0, 10, 5, 3]).reshape(-1, 1)))

[[ 0]
 [ 0]
 [10]
 [ 5]
 [ 3]]


# Slicing

In [73]:
arr_2d[0]

array([0.21057858, 0.56604212, 0.84251317, 0.90313239, 0.9501487 ])

In [75]:
arr_2d[0, 0]

np.float64(0.21057858087447745)

In [76]:
arr_2d[0,:3]

array([0.21057858, 0.56604212, 0.84251317])

In [77]:
arr_2d[0,::2]

array([0.21057858, 0.84251317, 0.9501487 ])

In [78]:
arr_2d[::2,::2]

array([[0.21057858, 0.84251317, 0.9501487 ],
       [0.08998153, 0.40481135, 0.40786524],
       [0.70903705, 0.20171277, 0.32202554]])

In [79]:
arr_2d[:, 0]

array([0.21057858, 0.46818483, 0.08998153, 0.0379207 , 0.70903705])

In [80]:
arr_2d[-1, -1]

np.float64(0.32202554442538456)

In [81]:
my_lst = [list(range(3)) for _ in range(3)]
my_lst

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [82]:
try:
    my_lst[:, -1]
except Exception as err:
    print(err)

list indices must be integers or slices, not tuple


# Boolean Indexing

In [144]:
arr_2d = np.random.randint(1, 10, (5, 5))
arr_2d

array([[1, 5, 1, 4, 8],
       [6, 7, 8, 9, 2],
       [7, 8, 2, 5, 4],
       [7, 9, 8, 3, 5],
       [7, 9, 9, 1, 7]])

In [145]:
arr_2d > 3

array([[False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [146]:
arr_2d[arr_2d > 3]

array([5, 4, 8, 6, 7, 8, 9, 7, 8, 5, 4, 7, 9, 8, 5, 7, 9, 9, 7])

In [147]:
cond1 = arr_2d > 3
cond2 = arr_2d < 5
arr_2d[cond1 & cond2]

array([4, 4])

In [148]:
cond1

array([[False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [149]:
cond2

array([[ True, False,  True,  True, False],
       [False, False, False, False,  True],
       [False, False,  True, False,  True],
       [False, False, False,  True, False],
       [False, False, False,  True, False]])

In [150]:
cond1 & cond2

array([[False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [151]:
cond1 | cond2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Operateurs logiques

* and -> en c/c#/java &&
* or -> en c/c#/java ||
* not -> en c/c#/java !

## Bitwise

* &
* |
* ^
* ~

Numpy utilise les bitwise pour faire des opérations boolean de filtrage sur un tableau.

In [152]:
cond1 ^ cond2

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# IN

In [153]:
np.isin(arr_2d, [2, 5])

array([[False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False,  True,  True, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [154]:
arr_2d[np.isin(arr_2d, [1, 5])]

array([1, 5, 1, 5, 5, 1])

In [155]:
arr_2d[np.isin(arr_2d, [1, 5])] = arr_2d.mean()

arr_2d

array([[5, 5, 5, 4, 8],
       [6, 7, 8, 9, 2],
       [7, 8, 2, 5, 4],
       [7, 9, 8, 3, 5],
       [7, 9, 9, 5, 7]])

Bien faire attention à la taille du tableau !

In [156]:
try:
    cond3 = [True, False, True]
    arr_2d[cond3]
except Exception as err:
    print(err)

boolean index did not match indexed array along axis 0; size of axis is 5 but size of corresponding boolean axis is 3


In [157]:
try:
    raise ValueError("ValueError")
except Exception as err:
    print(err)

ValueError


# Where

In [158]:
np.where(arr_2d > 3, arr_2d, np.nan)
# Condition -> arr_2d > 3
# Résultat si vrais -> arr_2d donc la valeur contenue à l'index
# Résultat si faux -> np.nan

array([[ 5.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8., nan,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [159]:
np.where(arr_2d > 3, arr_2d * 10, np.nan)

array([[50., 50., 50., 40., 80.],
       [60., 70., 80., 90., nan],
       [70., 80., nan, 50., 40.],
       [70., 90., 80., nan, 50.],
       [70., 90., 90., 50., 70.]])

# Argmax Et Argmin

In [160]:
np.argmax(arr_2d) # Sur ligne

np.int64(8)

In [161]:
np.argmax(arr_2d[4]) # Sur ligne

np.int64(1)

In [162]:
np.argmax(arr_2d[:,4]) # Sur colonne

np.int64(0)

In [163]:
arr_2d

array([[5, 5, 5, 4, 8],
       [6, 7, 8, 9, 2],
       [7, 8, 2, 5, 4],
       [7, 9, 8, 3, 5],
       [7, 9, 9, 5, 7]])

In [164]:
np.argmin(arr_2d[:,4]) # Sur colonne

np.int64(1)

In [167]:
arr_2d = arr_2d.astype(np.float64)
arr_2d[arr_2d == 2] = np.nan

In [169]:
arr_2d

array([[ 5.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [171]:
np.argmin(arr_2d[:,4])

np.int64(1)

# Ignorer les NaN avec nanargmax et nanargmin

In [170]:
np.nanargmin(arr_2d[:,4])

np.int64(2)

# Copy vs View

In [172]:
view = arr_2d[:2,:2]
view

array([[5., 5.],
       [6., 7.]])

In [173]:
view[0, 0] = 99
view

array([[99.,  5.],
       [ 6.,  7.]])

In [175]:
arr_2d

array([[99.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [176]:
copy = arr_2d[:2, :2].copy()
copy

array([[99.,  5.],
       [ 6.,  7.]])

In [177]:
copy[0, 0] = -1
copy

array([[-1.,  5.],
       [ 6.,  7.]])

In [178]:
arr_2d

array([[99.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

# Aggregation

In [183]:
arr_2d[arr_2d == np.nan] = 5
arr_2d

array([[99.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [194]:
arr_2d[np.isnan(arr_2d)] = 2
arr_2d

array([[99.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9.,  2.],
       [ 7.,  8.,  2.,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [195]:
arr_2d.sum()

np.float64(248.0)

In [197]:
arr_2d[arr_2d == 2] = np.nan
arr_2d

array([[99.,  5.,  5.,  4.,  8.],
       [ 6.,  7.,  8.,  9., nan],
       [ 7.,  8., nan,  5.,  4.],
       [ 7.,  9.,  8.,  3.,  5.],
       [ 7.,  9.,  9.,  5.,  7.]])

In [198]:
arr_2d.sum()

np.float64(nan)

In [202]:
arr_2d[~np.isnan(arr_2d)]

array([99.,  5.,  5.,  4.,  8.,  6.,  7.,  8.,  9.,  7.,  8.,  5.,  4.,
        7.,  9.,  8.,  3.,  5.,  7.,  9.,  9.,  5.,  7.])

In [201]:
arr_2d[~np.isnan(arr_2d)].sum()

np.float64(244.0)

In [203]:
arr_2d[~np.isnan(arr_2d)].mean()

np.float64(10.608695652173912)

In [204]:
arr_2d[~np.isnan(arr_2d)].cumsum()

array([ 99., 104., 109., 113., 121., 127., 134., 142., 151., 158., 166.,
       171., 175., 182., 191., 199., 202., 207., 214., 223., 232., 237.,
       244.])

In [205]:
arr_2d[~np.isnan(arr_2d)].std()

np.float64(18.927181122797936)

In [206]:
np.nansum(arr_2d)

np.float64(244.0)

In [207]:
np.nanmean(arr_2d)

np.float64(10.608695652173912)

# ufunc => Universal functions

In [208]:
np.isnan(arr_2d)

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [209]:
np.exp(0)

np.float64(1.0)

In [210]:
np.exp(arr_2d)

array([[9.88903032e+42, 1.48413159e+02, 1.48413159e+02, 5.45981500e+01,
        2.98095799e+03],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
                   nan],
       [1.09663316e+03, 2.98095799e+03,            nan, 1.48413159e+02,
        5.45981500e+01],
       [1.09663316e+03, 8.10308393e+03, 2.98095799e+03, 2.00855369e+01,
        1.48413159e+02],
       [1.09663316e+03, 8.10308393e+03, 8.10308393e+03, 1.48413159e+02,
        1.09663316e+03]])

# Concatener

In [212]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_concat = np.concatenate(
    [arr_1, arr_2, arr_3],
)

arr_concat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
arr_concat = np.concatenate(
    [
        arr_1.reshape(1, -1),
        arr_2.reshape(1, -1),
        arr_3.reshape(1, -1)
    ],
)

arr_concat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
arr_concat = np.concatenate(
    [
        arr_1.reshape(1, -1),
        arr_2.reshape(1, -1),
        arr_3.reshape(1, -1)
    ],
    axis=0
)

arr_concat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [217]:
arr_concat = np.concatenate(
    [
        arr_1.reshape(-1, 1),
        arr_2.reshape(-1, 1),
        arr_3.reshape(-1, 1)
    ],
    axis=1
)

arr_concat

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [221]:
arr_concat = np.concatenate(
    [
        arr_1.reshape(-1, 1),
        arr_1.reshape(-1, 1),
        arr_2.reshape(-1, 1),
        arr_2.reshape(-1, 1),
        arr_3.reshape(-1, 1),
        arr_3.reshape(-1, 1),
    ],
    axis=1
)

arr_concat

array([[1, 1, 4, 4, 7, 7],
       [2, 2, 5, 5, 8, 8],
       [3, 3, 6, 6, 9, 9]])

In [222]:
np.unique(arr_concat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])