# Algèbre linéaire avec NumPy

L'algèbre linéaire est une branche mathématique qui est centrale et indispensable pour les mathématiciens, scientifiques et informaticiens. 

Les points qui ont le plus d'applications sonts les derniers, il faut donc être patient avant de les aborder.
Si vous deviez ne pas avoir assez de temps et/ou de motivation pour l'intégralité de cette matière-ci,concentrez-vous sur les premiers points:
- ce sont les fondamentaux
- cela introduits la/les notations que vous allez retrouver ailleurs
- ce sont des prérequis (conceptuels) pour les points suivants et/ou cours suivants



## Les points importants (dans l'ordre): 
- Les definitions fondamentales
    - fonctions linéaires
    - vecteurs et somme de vecteurs
    - matrices et somme de matrices
    - multiplication de vecteur/matrices et produit scalaire

- Calculs et propriétés de vecteurs
    - transpose
    - taille d'un vecteur 
    - distances Euclidiennes
    - orthogonalité des vecteurs
    - orthonormalité des vecteurs
    - angles et cos
    - bases
    - projection de vecteurs
    - applications:
        - cosine-similarity
        - changement de coordonnées: process Gram-Schmidt

- Calculs et propriétés de matrices:
    - non-commutativité
    - inverse
    - trace
    - comatrice
    - déterminant
    - calculer la matrice inverse
    - applications:
        - résoudre sytèmes d'equations "en bloc"

- Theorie spectrale (en algèbre linéaire)
    - valeurs propres
    - vecteurs propres
    - determiner les valeurs et vecteurs propres
    - nombres complexes
    - applications:
        - construction de nouvelles coordonnées/références: diagonalisations


https://numpy.org/doc/stable/reference/routines.linalg.html

In [1]:
import numpy as np

$\newcommand{\vect}[1]{\vec{\mathbf{\boldsymbol{{#1}}}}}$
$\newcommand{\p}{{\cdot}}$
$\newcommand{\R}{{\mathbb{R}}}$
# 1. Définitions fondamentales
## 1.1 Fonctions linéaires

l'idée principale d'une fonction/application linéaire  $f(x)$ c'est qu'elle a les propriétés suivantes:
- $f(x+y) = f(x) + f(y)$
- $f(a \p x) = a \p f(x)$
    - donc quand on remplace $x$ par un multiple de celui-ci $y=a\cdot x$, le résultat final de la fonction n'est rien d'autre que le même multiple du résultat $f(x)$
    - peu importe les valeurs de $x$
    - une formule générale:
        - $f(a\p x+b\p y) = a \p f(x) + b \p f(y)$


Pour ici: $a,b,c,x,y,z$ sont des nombre rééls ($\R$) (= nombre avec décimales pour faire simple).  
Les fonction suivantes sont **strictement linéaires** :
- $f(x)= a \p x$:

    - demonstration:
        - $f(x+y) = a \p (x+y) = a \p x + a\p y = f(x) + f(y)$
        - $f(b\p x) = a\p(b\p x) = a\p b \p x  = b \p (a\p x) = b \p f(x)$

- $g(x,y) = a\p x + b\p y$
- $h(x,y,z) =  a\p x + b\p y + c\p x$


En bref ce sont des fonction  très simples. L'intérét de l'algèbre linéaire (les maths qui étudie ces structures de ce genre-là) c'est d'avoir des techniques/méthodologies/algorithmes qui permettent de les traiter en un (très) grand nombre à la fois. 

exemple:
- on souhaite résoudre le système d'equations suivant:
    - $3 x + 5 y + 2 z = 0$
    - $2 x + 6 y + 1 z = 1$
    - $4 x + 4 y + 3 z = 2$
-  on pourrais résoudre ce problème par substitution ($z=f(x,y), y = g(x)$)
    - cependant, quand on a beaucoup plus que 3 variables cela devient très vite très laborieux !
- on pourrais faire des combinaisons des equation jusqu'à obtenir $x=...,y=...,z=...$
    - souvant il faut chercher les bonnes combinaisons qui permettent de simplifier le système d'équations 
- l'altérnative, c'est  d'utiliser des techiques d'algèbre linéaire pour résoudre ces equations en "bloc"
    - = plus systématique et plus rapide (quand on a un grand nombre de variables $x,y,z,...$), mais également plus abstrait.
    - cette methode est conceptuellement similaire à la deuxième option, mais plus systématique



In [2]:
def f(x,a=3):
    return a*x
x = 2
c = 5
print(f(c*x) == c*f(x))

True


In [3]:
def g(x,a=3,b=1):
    return a*x+b
x = 2
c = 5
print(g(c*x) == c*g(x))

False


## 1.2 Vecteurs
- EN: vector


les valeurs $ a, b,  x_0, x_1, y_0, y_1, z_0, z_1$ sont des nombres réels $\R$ (nombre avec décimales)

si $X, Y$ sont des vecteur avec 2 dimensions (= une matrice avec $2\times 1$ dimensions)

$ X= 
\begin{bmatrix}
    x_0 \\
    x_1 
\end{bmatrix} = x_0 \p \vect{1}_0 + x_1 \p \vect{1}_1 \in \R^2 (\sim \R^{2,1} \sim  \R^{2,1,1} \sim ...) $  
$Y = 
\begin{bmatrix}
    y_0\\
    y_1 
\end{bmatrix} = y_0 \p \vect{1}_0 + y_1 \p \vect{1}_1 \in \R^2$ 

$
Z = a \cdot X + b \cdot Y
\\ =  a \cdot \begin{bmatrix}
    x_0 \\
    x_1 
\end{bmatrix} + 
b \cdot \begin{bmatrix}
    y_0\\
    y_1 
\end{bmatrix} 
\\ =   \begin{bmatrix}
    a \cdot x_0 \\
    a \cdot x_1 
\end{bmatrix} + 
 \begin{bmatrix}
    b \cdot y_0\\
    b \cdot y_1 
\end{bmatrix} 
\\ = \begin{bmatrix}
    a \cdot x_0 + b \cdot y_0\\
    a \cdot x_1 + b \cdot y_1 
\end{bmatrix} 
\\ = \begin{bmatrix}
    z_0 \\
    z_1 
\end{bmatrix} 
$ 

alors $Z$ l'est également

**Les vecteurs, c'est comme les fonctions linéaires !**

exemple :


$
R = \begin{bmatrix}
    1 \\
    0 
\end{bmatrix},
U  = \begin{bmatrix}
    0 \\
    1 
\end{bmatrix}
$

$ X = 0.5 \cdot  R + 3 \cdot U = \begin{bmatrix}
    0.5 \\
    3 
\end{bmatrix}
$



In [4]:
R = np.array([1,0])
U = np.array([0,1])

X = 0.5*R+3*U
print('X=',X)

X= [0.5 3. ]



Pour l'instant l'intéret est limité (plus intéréssant plus tard), mais on peut reformuler le système d'équations en vecteurs :
- système:
    - $3 x + 5 y + 2 z = 0$
    - $2 x + 6 y + 1 z = 1$
    - $4 x + 4 y + 3 z = 2$
- vecteur:
    -  $ \begin{bmatrix}
        3 x + 5 y + 2 z \\
        2 x + 6 y + 1 z \\
        4 x + 4 y + 3 z
        \end{bmatrix}
     = \begin{bmatrix}
        0\\
        1\\
        2
        \end{bmatrix} $

## 1.3 Matrices
- EN: matrix  
- une matrice, c'est un vecteur avec $N_1\times N_2$ dimensions

Les matrices $M,N$ ont toutes les deux les dimension $(2,2)$  Ce sont des matrices carré (autant élément en lignes qu'en colonnes). 

$
M = \begin{bmatrix}
    m_{00} & m_{01}\\
    m_{10} & m_{11}
\end{bmatrix} \in \R^{2,2},
N = \begin{bmatrix}
    n_{00} & n_{01}\\
    n_{10} & n_{11}
\end{bmatrix}
$

$
M+\gamma \cdot N = 
\begin{bmatrix}
    m_{00} & m_{01}\\
    m_{10} & m_{11}
\end{bmatrix} + \gamma \cdot \begin{bmatrix}
    n_{00} & n_{01}\\
    n_{10} & n_{11}
\end{bmatrix} = 
\begin{bmatrix}
    m_{00}+\gamma \cdot n_{00} & m_{01}+\gamma \cdot n_{01}\\
    m_{10}+\gamma \cdot n_{10} & m_{11}+\gamma \cdot n_{11}
\end{bmatrix} 
$

Des matrices non-carré existes aussi, mais c'est moins utilisé:   
$P = [p_{ij}]_{[2,3]} = \begin{bmatrix}
    p_{00} & p_{01} & p_{02}\\
    p_{10} & p_{11} & p_{12}\\
\end{bmatrix} \in \R^{2,3}$



In [5]:
M = np.array([[0.5, 5 ],
              [  2, 4]])
I = np.array([[1,0],
              [0,1]])

M-0.1*I

array([[0.4, 5. ],
       [2. , 3.9]])


### la matrice d'identité
la matrice d'identité(=toujours carré) de dimension $N\times N$, souvant noté $I_N$,
est une matrice diagonale (avec que des élément sur la diagonale) dont les valeurs non-zero vallent 1:

- $I_3 = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$
- pourquoi seulement la "diagonale" et pourquoi "identité" ? -> voir plus bas.


In [6]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 1.4 multiplication de vecteurs et matrices : le produit scalaire
- EN: scalar product, dot product


on peut voir les **matrices comme des transformateur (linéaire) d'un vecteur** en un autre vecteur:

Avec $A,B$ des vecteurs 2D, il nous faut 4 valeurs pour traduire toutes les valeurs de $A$: $\{a_{i}\}$ en valeurs de $B$:  $\{b_{j}\}$ 

![](static/mapping_A_B.png)

cette transformation est exprimé/calculé par le produit scalaire entre matrices et/ou vecteurs

$ B = W \cdot A = \begin{bmatrix}
    w_{00} & w_{01}\\
    w_{10} & w_{11}
\end{bmatrix} \cdot
\begin{bmatrix}
    a_0 \\
    a_1 
\end{bmatrix} =
\begin{bmatrix}
    w_{00} \cdot a_0 + w_{01} \cdot a_1\\
    w_{10} \cdot a_0 + w_{11} \cdot a_1 
\end{bmatrix} =
\begin{bmatrix}
    b_0 \\
    b_1 
\end{bmatrix}
$  
  
les valeurs $w_{ij}$ représentent les pondération/facteur de conversion: 
- $w_{00}$ = combien de $a_0$ est transferré à $b_{0}$  
- $w_{01}$ = combien de $a_0$ est transferré à $b_{1}$  
- $w_{10}$ = combien de $a_1$ est transferré à $b_{0}$
- $w_{11}$ = combien de $a_1$ est transferré à $b_{1}$   

#### example:

$R = \begin{bmatrix}
    1 \\
    0 
\end{bmatrix} = [\rightarrow]$, 
$U  = \begin{bmatrix}
    0 \\
    1 
\end{bmatrix} = [\uparrow] $,
$L = \begin{bmatrix}
    -1 \\
    0 
\end{bmatrix} = [\leftarrow] $, 
$ D = \begin{bmatrix}
    0 \\
    -1 
\end{bmatrix} = [\downarrow] $

Si je veux avoir une transformation qui permet de faire un cycle (sens inversé des éguille de montre) R->U->L->D->R->...,
cela peut ce faire avec la matrice $W$ suivante:  
$W= \begin{bmatrix}
    0 & -1 \\
    1 & 0 
\end{bmatrix}$

In [30]:
R = np.array([1,0])
U = np.array([0,1])
L = -R
D = -U

W = np.array([[0,-1],[1,0]])

print(np.dot(W,R)) ## dot product
print('-'*50)
print(U==np.dot(W,R))
print(np.all(U == np.dot(W,R)))

print('-'*50)
print(W@R) ## equiv
print(np.matmul(W,R)) ## equiv

[0 1]
--------------------------------------------------
[ True  True]
True
--------------------------------------------------
[0 1]
[0 1]


In [32]:
try:
    [[0,1],[1,0]] @ [[1 ,0 ],[0,1]]
except Exception as err:
    print(err)

unsupported operand type(s) for @: 'list' and 'list'


In [8]:
def my_dot(A,B):
    C = np.zeros(shape=(A.shape[0],B.shape[1]),dtype=A.dtype)
    
    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            C[i,j] = np.sum(A[i,:]*B[:,j])
    
    return C

In [9]:
print(R.reshape(-1,1))

[[1]
 [0]]


In [10]:
print(my_dot(W,R.reshape(-1,1)))
print(U.reshape(-1,1))

[[0]
 [1]]
[[0]
 [1]]


#### la matrice d'identité
quand on multiplie n'importe quel vecteur (ou matrice) - qui a une dimension compatible - avec la matrice d'identité, on garde ce vecteur (ou matrice):
- $ \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1 & 0  \\
        0 & 0 & 1
        \end{bmatrix}
        \cdot 
        \begin{bmatrix}
        x\\
        y\\
        z
        \end{bmatrix}=
        \begin{bmatrix}
        x\\
        y\\
        z
        \end{bmatrix}$  

- $ \begin{bmatrix}
        1 & 0  \\
        0 & 1 \\
        \end{bmatrix}
        \cdot 
        \begin{bmatrix}
        a & b\\
        c & d\\
        \end{bmatrix}=
        \begin{bmatrix}
        a & b\\
        c & d\\
        \end{bmatrix}
  \p \begin{bmatrix}1 & 0  \\
        0 & 1 \\
        \end{bmatrix}
        =
        \begin{bmatrix}
        a & b\\
        c & d\\
        \end{bmatrix}$


In [11]:
print("I:\n",I,'\nM:\n',M)
print("-"*5)
print(np.all(I.dot(M) == M.dot(I)))
print(np.all(I.dot(M) == M))


I:
 [[1 0]
 [0 1]] 
M:
 [[0.5 5. ]
 [2.  4. ]]
-----
True
True


dans l'exemple avec $R,U,L,D$: quand on applique la transformation 4 fois on retrouve le vecteur initial:
- "appliquer 4 fois" = 4 fois la multiplication de $W$:
    - $ W^4 = W \p W\p W\p W $
- "on retrouve le vecteur initial" signifie qu'on obtiens la matrice d'identité toutes les 4 applications:
    - $ \begin{bmatrix}
    0 & -1 \\
    1 & 0 
\end{bmatrix} \p \begin{bmatrix}
    0 & -1 \\
    1 & 0 
\end{bmatrix} \p \begin{bmatrix}
    0 & -1 \\
    1 & 0 
\end{bmatrix} \p \begin{bmatrix}
    0 & -1 \\
    1 & 0 
\end{bmatrix} = \begin{bmatrix}
    1 & 0 \\
    0 & 1 
\end{bmatrix} $
        - faites le calcul pour vous convaincre de l'égalité

In [28]:
print(np.dot(W,W))
print("-"*5)
print(W.dot(W).dot(W).dot(W))
print("-"*5)
print(W@W@W@W)

[[-1  0]
 [ 0 -1]]
-----
[[1 0]
 [0 1]]
-----
[[1 0]
 [0 1]]


on peut à nouveau reformuler notre système d'équations:
- système:
    - $3 x + 5 y + 2 z = 0$
    - $2 x + 6 y + 1 z = 1$
    - $4 x + 4 y + 3 z = 2$
- vecteur:
    -  $ \begin{bmatrix}
        3 x + 5 y + 2 z \\
        2 x + 6 y + 1 z \\
        4 x + 4 y + 3 z
        \end{bmatrix}
     = \begin{bmatrix}
        0\\
        1\\
        2
        \end{bmatrix} $
- multiplication vecteur avec matrice:
    -  $ \begin{bmatrix}
        3 & 5 & 2  \\
        2 & 6 & 1  \\
        4 & 4 & 3
        \end{bmatrix}
        \cdot 
        \begin{bmatrix}
        x\\
        y\\
        z
        \end{bmatrix}
     = \begin{bmatrix}
        0\\
        1\\
        2
        \end{bmatrix} $
    -  $ \begin{bmatrix}
        3 & 5 & 2 & 0  \\
        2 & 6 & 1 & -1 \\
        4 & 4 & 3 & -2 \\
        \end{bmatrix}
        \cdot 
        \begin{bmatrix}
        x\\
        y\\
        z\\
        1
        \end{bmatrix}
     = \begin{bmatrix}
        0\\
        0\\
        0 \\
        \end{bmatrix} $

# 2. Calculs et propriétés de vecteurs

## 2.1 operation de transpose:

$A = \begin{bmatrix}
    a_0 \\
    a_1 
\end{bmatrix}$  

$A^T =  \begin{bmatrix}
    a_0 & a_1\\
\end{bmatrix} $

$P = \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6\\
\end{bmatrix} $  

$P^T = \begin{bmatrix}
    1 & 4\\
    2 & 5\\
    3 & 6
\end{bmatrix} $

In [13]:
print(M)
print('-'*12)
print(M.T)
print(np.transpose(M))

[[0.5 5. ]
 [2.  4. ]]
------------
[[0.5 2. ]
 [5.  4. ]]
[[0.5 2. ]
 [5.  4. ]]




## 2.2 Taille d'un vecteur


on peut réduire le vecteur à un nombre (=un scalaire) via le produit scalaire:  

$A^T \p A = 
    \begin{bmatrix}
    a_0 & a_1\\
\end{bmatrix} 
\p \begin{bmatrix}
    a_0 \\
    a_1 
\end{bmatrix} = \begin{bmatrix} (a_0)^2 + (a_1)^2\end{bmatrix}= (a_0)^2 + (a_1)^2 \in \R $ 
Cette valeur correspond à la taille (au carré) du vecteur $||A||^2$.


### un vecteur normé
un vecteur est dit "normé" quand sa taille vaut 1
- $||X||^2 = ||X|| = 1$

In [19]:
print("||X||^2   =",np.dot(X.T,X))
print('-'*50)
### dans numpy il n'est pas nécessaire de transposer un vecteur (mais bien une matrice ou objet avec len(shape)>1)
print(np.dot(X,X))
print(np.linalg.norm(X))

||X||^2   = 9.25
--------------------------------------------------
9.25
3.0413812651491097


In [15]:
np.dot(R,R) ## R est normé

1

## 2.3 Distances Euclidienne
Dans la même logique que la taille d'un vecteur, il est possible de calculer la distance (Euclidienne) entre deux vecteurs:

distance_carré = $||A-B||^2 = (a_0-b_0)^2 + (a_1-b_1)^2$ = $u_0^2 +u_1^2$  

(avec la substitution $u_i= (a_i - b_i)$ pour la simplicité)


$(A-B)^T \cdot (A-B) = \begin{bmatrix}
    (a_0 - b_0) & (a_1 - b_1)
\end{bmatrix} \cdot \begin{bmatrix}
    (a_0 -b_0) \\
    (a_1-b_1) 
\end{bmatrix}= \begin{bmatrix}
    u_0 & u_1\\
\end{bmatrix} \cdot \begin{bmatrix}
    u_0 \\
    u_1 
\end{bmatrix}= \begin{bmatrix}
    u_0 \cdot u_0 + u_1 \cdot u_1
\end{bmatrix}= u_0 ^2 + u_1^2 = ||A-B||^2$


In [20]:
print((R-U))
print((R-U).T)
print('-'*50)

dist_R_U_square = np.dot((R-U).T
                         ,(R-U)
                        )
dist_R_U = np.sqrt(dist_R_U_square)

print("||R-U||^2 =", dist_R_U_square)
print("||R-U||   =",dist_R_U)
print(np.linalg.norm(R-U))

[ 1 -1]
[ 1 -1]
--------------------------------------------------
||R-U||^2 = 2
||R-U||   = 1.4142135623730951
1.4142135623730951


## 2.4 Orthogonalité 

deux vecteurs sont orthogonaux si et seulement si le produit scalaire de ceux-ci est zero

**orthogonal = indépendance linéaire**

exemple:
- $ R = \begin{bmatrix}
    1 \\
    0 
\end{bmatrix}$et $
U  = \begin{bmatrix}
    0 \\
    1 
\end{bmatrix}$ sont orthogonaux:
    - $R^T \p U = U^T \p R = \begin{bmatrix}
    1 & 0 \\
\end{bmatrix} \p \begin{bmatrix}
    0 \\
    1 
\end{bmatrix} = \begin{bmatrix}
    (1\p 0)+ (0 \p 1) \\
\end{bmatrix} = 0$ 

- $ X = 0.5 \cdot  R + 3 \cdot U = \begin{bmatrix}
    0.5 \\
    3 
\end{bmatrix}$ et $R$ ne sont pas orthogonaux:
    - $R^T \p X = X^T \p R =   \begin{bmatrix}
    1 & 0 \\
\end{bmatrix} \p \begin{bmatrix}
    0.5 \\
    3 
\end{bmatrix} = \begin{bmatrix}
    (1\p 0.5)+ (0 \p 3) \\
\end{bmatrix} = 0.5$



In [17]:
print(R.dot(U))
print(R.dot(X))

0
0.5


## 2.5 Ortonormalité

deux vecteurs sont orthonormaux si et seulement si ils sont à la fois:
- ortogonaux : le produit scalaire est zero
- normés : la taille respective de chacun vaut 1

exemple:
- $R$ et $U$ :
    - sont déjà orthogonaux
    - $R^T \p R = 1$

- $A = \begin{bmatrix}
    1 \\
    1 
\end{bmatrix}$ et $B = \begin{bmatrix}
    1 \\
    -1 
\end{bmatrix}$:

    -  sont ortogonaux:
        - $A^T \p B = \begin{bmatrix}
    1 & 1 \\
\end{bmatrix} \p \begin{bmatrix}
    1 \\
    -1 
\end{bmatrix} = \begin{bmatrix}
    1\p 1+ 1 \p (-1) \\
\end{bmatrix} = 0$
    - ne sont pas normés:
        - $||A||^2 =  A^T \p A = \begin{bmatrix}
    1 & 1 \\
\end{bmatrix} \p \begin{bmatrix}
    1 \\
    1 
\end{bmatrix} = \begin{bmatrix}
    (1\p 1)+ (1 \p 1) \\
\end{bmatrix} = 2 \neq 1$ 

## angles entre vecteurs



## Projection de vecteurs

la projection de vecteur est le produit scalaire entre deux vecteurs $X,\hat{Y}$ permet de "compter"/calculer la proportionalité que $X$ a dans $Y$:
- $\text{proj}_Y(X) = X^T \p \hat{Y}$

- avec :
    - $\hat{Y} = \vect{1}_Y = \frac{Y}{||Y||} $

exemple:
- $X = \begin{bmatrix} 
    2 \\
     4
\end{bmatrix}, Y = \begin{bmatrix} 
    0 \\
     2 
\end{bmatrix}, \hat{Y} = \begin{bmatrix} 
    0 \\
     1 
\end{bmatrix}$
- $X^T \p \hat{Y} =  \begin{bmatrix} 
    2\p 0 + 4 \p 1
\end{bmatrix}  = 4$


## 2.6 Bases d'un espace vectoriel

### un espace vectoriel
pour simplifier, un espace vectoriel, c'est l'ensemble des vecteurs possible quand on fait des operations linéaire avec des vecteurs appartenant à celui-ci.
- **espace vectoriel = "champ des possibles"**

example:
- prenons $R$ et $U$ comme vecteurs initial, l'espace vectoriel pour ces vecteurs c'est $\R^2$:
    - avec $\forall x_0,x_1 \in \R$, je peux reconstruire n'importe quel vecteur $X = x_0 \p R + x_1\p U = \begin{bmatrix} 
    x_0 \\
    x_1 
\end{bmatrix} \in \R^2$
    - la dimension de cet espace vectoriel est 2 : $\dim(span(R,U))=2$
- prenons $R$ et $L = \begin{bmatrix} 
    -1 \\
     0
\end{bmatrix}$ comme vecteurs initial, l'espace vectoriel n'est que $\R^1$:
    - avec $\forall x_0,x_1 \in \R$, je ne peux reconstruire que $Y= x_0 \p R + x_1\p L = \begin{bmatrix} 
    x_0-x_1 \\
    0
\end{bmatrix} = \begin{bmatrix} 
    y_0 \\
    0
\end{bmatrix} \sim \R^1$
    - la dimension de cet espace vectoriel est 1: $\dim(span(R,L))=1$


Il existe donc des combinaisons de vecteurs qui permettent de construire des espace (=champ des possible) plus vastes que d'autres. 


### bases
Les vecteurs qui permettent d'avoir le plus grand espace vectoriel sont des vecteurs orthogonaux.
Pour un espace vectoriel, une base de cet espace c'est le plus petit ensemble de vecteurs orthonormaux qui permet de construire cet espace. le nombre de vecteurs nécessaire est egal au nombre de dimensions d'un vecteur.
- En gros: **pour ce faciliter la vie et** avoir quelque chose de suffisament **expressif**, on veux un ensemble de **vecteurs orthonormaux**.

exemple:
- les bases les plus simples (élémentaires/triviales):
    - $E_0 = \begin{bmatrix} 
    1 \\
     0
\end{bmatrix},E_1 = \begin{bmatrix} 
    0 \\
     1
\end{bmatrix} $ et similaire pour les les dimensions $N>2$
- possible:
    - $E^{'}_0 = \frac{1}{\sqrt{2}}\begin{bmatrix} 
    1 \\
     1
\end{bmatrix},E^{'}_1 = \frac{1}{\sqrt{2}}\begin{bmatrix} 
    1 \\
     -1
\end{bmatrix} $
 
    - $E^{''}_0 = \frac{1}{\sqrt{5}}\begin{bmatrix} 
    2 \\
     1
\end{bmatrix},E^{''}_1 = \frac{1}{\sqrt{5}}\begin{bmatrix} 
    1 \\
     -2
\end{bmatrix} $

   - $E^{'''}_0 = \frac{1}{\sqrt{2}}\begin{bmatrix} 
    1 \\
     1 \\
     0
\end{bmatrix},E^{'''}_1 = \frac{1}{\sqrt{2}}\begin{bmatrix} 
    1 \\
     -1\\
     0
     \end{bmatrix}, E^{'''}_2 = \begin{bmatrix} 
    0 \\
     0 \\
     1
     \end{bmatrix}$
 
  - etc.